apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    []
  mapUsers: |
    - userarn: arn:aws:iam::884825629456:root
      username: admin
      groups:
        - system:masters